"""Add new status to ResponseStatusEnum

Revision ID: a6fafb52e863
Revises: a2adaeb1f0c2
Create Date: 2025-12-12 20:44:16.135513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6fafb52e863'
down_revision: Union[str, Sequence[str], None] = 'a2adaeb1f0c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE responsestatusenum ADD VALUE 'IN_PROGRESS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
